Importng the libraries

In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Importing the dataset

In [246]:
file_path = 'H:\WEB_ECO\Web_Analyze_Economy\Data\Total.csv'
df = pd.read_csv(file_path, encoding = 'ISO-8859-1')
df.head()

<>:1: SyntaxWarning: invalid escape sequence '\W'
<>:1: SyntaxWarning: invalid escape sequence '\W'
C:\Users\admin\AppData\Local\Temp\ipykernel_10448\3147051908.py:1: SyntaxWarning: invalid escape sequence '\W'
  file_path = 'H:\WEB_ECO\Web_Analyze_Economy\Data\Total.csv'

,STT,Country,Continents,Rate of users Internet (%),Mobile device usage (%),Revenue of ecommerce platforms (billion USD),Revenue of IT industry (billion USD),Funding in digital infrastructure (billion USD),Foreign investment capital (billion USD),CREDIT and BANKING digital transformation ratio(%),Number of Enterprises Applying Digital Transformation (bussiness),Economic Growth Rate of Education (% GDP),Number of technology start up businesses,Year
0,1,Algeria,Africa,20.0,97.0,0.50,0.80,0.10,1.50,0.0,12000,4.1,800,2014
1,2,Angola,Africa,15.0,44.3,0.25,0.37,0.10,3.66,12.8,15000,3.5,170,2014
2,3,Benin,Africa,13.0,55.0,0.12,0.07,0.10,0.41,0.0,10000,3.5,80,2014
3,4,Botswana,Africa,21.0,77.0,0.20,0.20,0.07,0.52,0.0,18000,6.0,280,2014
4,5,Burkina Faso,Africa,4.5,65.5,0.10,0.10,0.06,0.36,0.0,8000,4.0,55,2014

In [247]:
df2 = df.drop('STT',axis='columns')
df2.head()

,Country,Continents,Rate of users Internet (%),Mobile device usage (%),Revenue of ecommerce platforms (billion USD),Revenue of IT industry (billion USD),Funding in digital infrastructure (billion USD),Foreign investment capital (billion USD),CREDIT and BANKING digital transformation ratio(%),Number of Enterprises Applying Digital Transformation (bussiness),Economic Growth Rate of Education (% GDP),Number of technology start up businesses,Year
0,Algeria,Africa,20.0,97.0,0.50,0.80,0.10,1.50,0.0,12000,4.1,800,2014
1,Angola,Africa,15.0,44.3,0.25,0.37,0.10,3.66,12.8,15000,3.5,170,2014
2,Benin,Africa,13.0,55.0,0.12,0.07,0.10,0.41,0.0,10000,3.5,80,2014
3,Botswana,Africa,21.0,77.0,0.20,0.20,0.07,0.52,0.0,18000,6.0,280,2014
4,Burkina Faso,Africa,4.5,65.5,0.10,0.10,0.06,0.36,0.0,8000,4.0,55,2014

Cleaning data

In [206]:
#Kiểm tra và thay thế các giá trị không hợp lệ
import pandas as pd
import numpy as np
df2.replace(' - ', np.nan, inplace=True) 
df2.dropna(inplace=True)

In [204]:
print(df2.columns)

Index(['Country', 'Continents', 'Rate of users Internet (%)',
       'Mobile device usage (%)',
       'Revenue of ecommerce platforms (billion USD)',
       'Revenue of IT industry (billion USD)',
       'Funding in digital infrastructure (billion USD)',
       'Foreign investment capital (billion USD)',
       'CREDIT and BANKING digital transformation ratio(%)',
       'Number of Enterprises Applying Digital Transformation (bussiness)',
       'Economic Growth Rate of Education (% GDP)',
       'Number of technology start up businesses', 'Year'],
      dtype='object')

In [256]:
# Chuyển đổi các cột cần thiết sang kiểu số
cols_to_convert = ['Rate of users Internet (%)', 'Mobile device usage (%)', 'Revenue of ecommerce platforms (billion USD)', 
                   'Revenue of IT industry (billion USD)', 'Funding in digital infrastructure (billion USD)', 
                   'Foreign investment capital (billion USD)', 'CREDIT and BANKING digital transformation ratio(%)', 
                   'Number of Enterprises Applying Digital Transformation (bussiness)', 
                   'Economic Growth Rate of Education (% GDP)', 'Number of technology start up businesses']

for col in cols_to_convert:
    df2[col] = pd.to_numeric(df2[col], errors='coerce')

df2.dropna(inplace=True)  # Loại bỏ các hàng chứa NaN sau khi chuyển đổi

In [257]:
X = df2[cols_to_convert].values
y = df2['Year'].values

Splitting the dataset into the Training set and Test set

In [258]:
#check null 
null_values = df2.isnull().sum()

# Value = 0
zero_values = (df2 == 0).sum()

print("The numbers is null:\n", null_values)
print("\n Equal 0 :\n", zero_values)

The numbers is null:
 Country                                                              0
Continents                                                           0
Rate of users Internet (%)                                           0
Mobile device usage (%)                                              0
Revenue of ecommerce platforms (billion USD)                         0
Revenue of IT industry (billion USD)                                 0
Funding in digital infrastructure (billion USD)                      0
Foreign investment capital (billion USD)                             0
CREDIT and BANKING digital transformation ratio(%)                   0
Number of Enterprises Applying Digital Transformation (bussiness)    0
Economic Growth Rate of Education (% GDP)                            0
Number of technology start up businesses                             0
Year                                                                 0
dtype: int64

 Equal 0 :
 Country                                                                0
Continents                                                             0
Rate of users Internet (%)                                             0
Mobile device usage (%)                                                0
Revenue of ecommerce platforms (billion USD)                           1
Revenue of IT industry (billion USD)                                  23
Funding in digital infrastructure (billion USD)                      121
Foreign investment capital (billion USD)                              65
CREDIT and BANKING digital transformation ratio(%)                   383
Number of Enterprises Applying Digital Transformation (bussiness)      0
Economic Growth Rate of Education (% GDP)                              0
Number of technology start up businesses                               0
Year                                                                   0
dtype: int64